# name: Update commit graph

# on:
#   push:
#     branches: [ main, F811, T01 ]
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout full history
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0 # Historial

#       - name: Update README commit graph
#         run: |
#           bash scripts/update-graph.sh
#           if ! git diff --quiet; then
#             git config user.name "github-actions[bot]"
#             git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
#             git add README.md || true
#             git add F811-FC/README.md || true
#             git commit -m "chore: update commit graphs"
#             git push
#           else
#             echo "Sin cambios en los README.md"
#           fi

name: Build commit graph SVGs

on:
  push:          # se ejecuta con cualquier rama nueva o commits
  workflow_dispatch:

jobs:
  build-commit-graphs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # necesario para ver toda la historia y ramas

      - name: Generate SVG (ALL branches)
        env:
          OUTPUT: assets/commit-graph.svg
          # LINE_LIMIT: "200"         # opcional: limitar a 200 commits (ajusta o elimina)
          THEME: dark
        run: |
          python3 scripts/commit_graph_svg.py

      - name: Generate SVG (F811 + Txx + xxxx)
        env:
          BRANCH_REGEX: '(^F811$)|(^T[0-9]+$)|(^x[0-9]+$)|(/F811$)'
          OUTPUT: assets/commit-graph-f811.svg
          # LINE_LIMIT: "200"
          THEME: dark
        run: |
          python3 scripts/commit_graph_svg.py

      - name: Commit & push SVGs if changed
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add assets/commit-graph.svg assets/commit-graph-f811.svg
            git commit -m "chore: update commit graph SVGs"
            git push
          else
            echo "Sin cambios en SVGs."
          fi
